
const STORAGE_KEY = "materiiPrime";

if (!localStorage.getItem(STORAGE_KEY)) {
  const materialeInitiale = [
    {
      id: 1,
      denumire: "Malt Pale Ale",
      tip: "malt",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Malt",
      codProdus: "MALT-001",
      lot: "",
    },
    {
      id: 2,
      denumire: "Malt",
      tip: "malt",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Malt",
      codProdus: "MALT-002",
      lot: "",
    },
    {
      id: 3,
      denumire: "Drojdie Fermentis BE-256",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-001",
      lot: "",
    },
    {
      id: 4,
      denumire: "Drojdie Fermentis F-2",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-002",
      lot: "",
    },
    {
      id: 5,
      denumire: "Hamei AMAREALA",
      tip: "hamei",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-001",
      lot: "",
    },
    {
      id: 6,
      denumire: "Hamei AROMA",
      tip: "hamei",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-002",
      lot: "",
    },
    {
      id: 7,
      denumire: "Irish moss",
      tip: "aditiv",
      cantitate: 0,
      unitate: "pachete",
      producator: "Generic Additives",
      codProdus: "ADITIV-001",
      lot: "",
    },
    {
      id: 8,
      denumire: "Zahăr brun",
      tip: "aditiv",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Additives",
      codProdus: "ADITIV-002",
      lot: "",
    },
    {
      id: 9,
      denumire: "Sticlă 0.5L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-001",
      lot: "",
    },
    {
      id: 10,
      denumire: "Keg 50L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-002",
      lot: "",
    },
    {
      id: 11,
      denumire: "Capac",
      tip: "accesoriu",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "ACCESORIU-001",
      lot: "",
    },
    {
      id: 12,
      denumire: "Etichetă față",
      tip: "accesoriu",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "ACCESORIU-002",
      lot: "",
    },
    {
      id: 13,
      denumire: "Weyermann Carafa Special Type 1",
      tip: "malt prăjit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-003",
      lot: "",
    },
    {
      id: 14,
      denumire: "Weyermann Carafa Type 1",
      tip: "malt prăjit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-004",
      lot: "",
    },
    {
      id: 15,
      denumire: "Weyermann Chocolate Rye",
      tip: "malt prăjit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-005",
      lot: "",
    },
    {
      id: 16,
      denumire: "Weyermann Chocolate Wheat",
      tip: "malt grâu prăjit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-006",
      lot: "",
    },
    {
      id: 17,
      denumire: "Fulgi de orz/ovăz",
      tip: "fulgi",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Cereals",
      codProdus: "FULGI-001",
      lot: "",
    },
    {
      id: 18,
      denumire: "Coji de orez",
      tip: "aditiv",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Additives",
      codProdus: "ADITIV-003",
      lot: "",
    },
    {
      id: 19,
      denumire: "Weyermann® CaraPils®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-007",
      lot: "",
    },
    {
      id: 20,
      denumire: "Weyermann® CaraHell®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-008",
      lot: "",
    },
    {
      id: 21,
      denumire: "Weyermann® CaraBelge®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-009",
      lot: "",
    },
    {
      id: 22,
      denumire: "Weyermann® CaraRed®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-010",
      lot: "",
    },
    {
      id: 23,
      denumire: "Weyermann® CaraAmber®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-011",
      lot: "",
    },
    {
      id: 24,
      denumire: "Weyermann® CaraMunich® type I",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-012",
      lot: "",
    },
    {
      id: 25,
      denumire: "Weyermann® CaraMunich® type II",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-013",
      lot: "",
    },
    {
      id: 26,
      denumire: "Weyermann® CaraMunich® type III",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-014",
      lot: "",
    },
    {
      id: 27,
      denumire: "Weyermann® CaraBohemian®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-015",
      lot: "",
    },
    {
      id: 28,
      denumire: "Weyermann® CaraAroma®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-016",
      lot: "",
    },
    {
      id: 29,
      denumire: "Weyermann® CaraRye®",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-017",
      lot: "",
    },
    {
      id: 30,
      denumire: "Brewferm Special B",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Brewferm",
      codProdus: "MALT-018",
      lot: "",
    },
    {
      id: 31,
      denumire: "Crisp Crystal 100",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Crisp Malting",
      codProdus: "MALT-019",
      lot: "",
    },
    {
      id: 32,
      denumire: "Crisp Crystal 150",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Crisp Malting",
      codProdus: "MALT-020",
      lot: "",
    },
    {
      id: 33,
      denumire: "Crisp Crystal 240",
      tip: "malt",
      subcategorie: "caramelizat",
      cantitate: 0,
      unitate: "kg",
      producator: "Crisp Malting",
      codProdus: "MALT-021",
      lot: "",
    },
    {
      id: 34,
      denumire: "Malt de orz Castle Malting Chocolate",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Castle Malting",
      codProdus: "MALT-022",
      lot: "",
    },
    {
      id: 35,
      denumire: "Weyermann® Carafa® Type 1",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-023",
      lot: "",
    },
    {
      id: 36,
      denumire: "Weyermann® Carafa® Type 2",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-024",
      lot: "",
    },
    {
      id: 37,
      denumire: "Weyermann® Carafa Special® Type 1",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-025",
      lot: "",
    },
    {
      id: 38,
      denumire: "Weyermann® Carafa Special® Type 2",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-026",
      lot: "",
    },
    {
      id: 39,
      denumire: "Weyermann® Carafa Special® Type 3",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-027",
      lot: "",
    },
    {
      id: 40,
      denumire: "Weyermann® Chocolate Rye",
      tip: "malt",
      subcategorie: "prajit",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-028",
      lot: "",
    },
    {
      id: 42,
      denumire: "Weyermann® Acidulated",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-029",
      lot: "",
    },
    {
      id: 43,
      denumire: "Weyermann® Melanoidin",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-030",
      lot: "",
    },
    {
      id: 44,
      denumire: "Weyermann® Abbey®",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-031",
      lot: "",
    },
    {
      id: 45,
      denumire: "Weyermann® Special W®",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-032",
      lot: "",
    },
    {
      id: 46,
      denumire: "Weyermann® Beech Smoked",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-033",
      lot: "",
    },
    {
      id: 47,
      denumire: "Weyermann® Rye",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-034",
      lot: "",
    },
    {
      id: 48,
      denumire: "Brewferm Biscuit",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Brewferm",
      codProdus: "MALT-035",
      lot: "",
    },
    {
      id: 49,
      denumire: "Brewferm Whisky",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Brewferm",
      codProdus: "MALT-036",
      lot: "",
    },
    {
      id: 50,
      denumire: "Crisp Naked Oats",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Crisp Malting",
      codProdus: "MALT-037",
      lot: "",
    },
    {
      id: 51,
      denumire: "Weyermann® Wheat Dark",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-038",
      lot: "",
    },
    {
      id: 52,
      denumire: "Weyermann® Wheat Pale",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-039",
      lot: "",
    },
    {
      id: 53,
      denumire: "Weyermann® CaraWheat®",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-040",
      lot: "",
    },
    {
      id: 54,
      denumire: "Weyermann® Chocolate Wheat",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-041",
      lot: "",
    },
    {
      id: 55,
      denumire: "Weyermann® Oak Smoked Wheat",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-042",
      lot: "",
    },
    {
      id: 56,
      denumire: "Weyermann® Spelt",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-043",
      lot: "",
    },
    {
      id: 57,
      denumire: "Weyermann® Diastatic Barley",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-044",
      lot: "",
    },
    {
      id: 58,
      denumire: "Weyermann® Diastatic Wheat",
      tip: "malt",
      subcategorie: "special",
      cantitate: 0,
      unitate: "kg",
      producator: "Weyermann",
      codProdus: "MALT-045",
      lot: "",
    },
    {
      id: 59,
      denumire: "AMARILLO 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-003",
      lot: "",
    },
    {
      id: 60,
      denumire: "AZACCA® P01594 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-004",
      lot: "",
    },
    {
      id: 61,
      denumire: "CASCADE USA 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-005",
      lot: "",
    },
    {
      id: 62,
      denumire: "CENTENNIAL 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-006",
      lot: "",
    },
    {
      id: 63,
      denumire: "CHALLENGER 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-007",
      lot: "",
    },
    {
      id: 64,
      denumire: "CHINOOK 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-008",
      lot: "",
    },
    {
      id: 65,
      denumire: "CITRA 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-009",
      lot: "",
    },
    {
      id: 66,
      denumire: "COLUMBUS 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-010",
      lot: "",
    },
    {
      id: 67,
      denumire: "EAST KENT GOLDINGS 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-011",
      lot: "",
    },
    {
      id: 68,
      denumire: "EL DORADO 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-012",
      lot: "",
    },
    {
      id: 69,
      denumire: "ELIXIR ALSACIA 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-013",
      lot: "",
    },
    {
      id: 70,
      denumire: "FUGGLES 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-014",
      lot: "",
    },
    {
      id: 71,
      denumire: "GALAXY 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-015",
      lot: "",
    },
    {
      id: 72,
      denumire: "HALLERTAU BLANC 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-016",
      lot: "",
    },
    {
      id: 73,
      denumire: "HALLERTAU MITTELFRUH 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-017",
      lot: "",
    },
    {
      id: 74,
      denumire: "HALLERTAU PERLE 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-018",
      lot: "",
    },
    {
      id: 75,
      denumire: "HBC 630 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-019",
      lot: "",
    },
    {
      id: 76,
      denumire: "IDAHO 7™ 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-020",
      lot: "",
    },
    {
      id: 77,
      denumire: "KAZBEK 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-021",
      lot: "",
    },
    {
      id: 78,
      denumire: "LEMONDROP™ 2022",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-022",
      lot: "",
    },
    {
      id: 79,
      denumire: "MAGNUM 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-023",
      lot: "",
    },
    {
      id: 80,
      denumire: "MANDARINA BAVARIA 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-024",
      lot: "",
    },
    {
      id: 81,
      denumire: "MOSAIC 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-025",
      lot: "",
    },
    {
      id: 82,
      denumire: "MOTUEKA™ 2022",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-026",
      lot: "",
    },
    {
      id: 83,
      denumire: "NECTARON® 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-027",
      lot: "",
    },
    {
      id: 84,
      denumire: "NORTHERN BREWER 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-028",
      lot: "",
    },
    {
      id: 85,
      denumire: "POLARIS 2022",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-029",
      lot: "",
    },
    {
      id: 86,
      denumire: "SAAZ 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-030",
      lot: "",
    },
    {
      id: 87,
      denumire: "SABRO® 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-031",
      lot: "",
    },
    {
      id: 88,
      denumire: "SIMCOE 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Yakima Chief",
      codProdus: "HAMEI-032",
      lot: "",
    },
    {
      id: 89,
      denumire: "STYRIAN AURORA 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-033",
      lot: "",
    },
    {
      id: 90,
      denumire: "STYRIAN GOLDING 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-034",
      lot: "",
    },
    {
      id: 91,
      denumire: "STYRIAN KOLIBRI 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-035",
      lot: "",
    },
    {
      id: 92,
      denumire: "TETTNANGER 2024",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-036",
      lot: "",
    },
    {
      id: 93,
      denumire: "VIC SECRET 2023",
      tip: "hamei",
      subcategorie: "peleti",
      cantitate: 0,
      unitate: "kg",
      producator: "Generic Hops",
      codProdus: "HAMEI-037",
      lot: "",
    },
    {
      id: 94,
      denumire: "Fermentis SafAle BE-134",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-003",
      lot: "",
    },
    {
      id: 95,
      denumire: "Fermentis SafAle K-97",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-004",
      lot: "",
    },
    {
      id: 96,
      denumire: "Fermentis SafBrew S-33",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-005",
      lot: "",
    },
    {
      id: 97,
      denumire: "Fermentis SafBrew T-58",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-006",
      lot: "",
    },
    {
      id: 98,
      denumire: "Fermentis SafAle S-04",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-007",
      lot: "",
    },
    {
      id: 99,
      denumire: "Fermentis SafAle US-05",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-008",
      lot: "",
    },
    {
      id: 100,
      denumire: "Fermentis SafAle WB-06",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-009",
      lot: "",
    },
    {
      id: 101,
      denumire: "Fermentis SafLager S-23",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-010",
      lot: "",
    },
    {
      id: 102,
      denumire: "Fermentis SafLager W-34/70",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-011",
      lot: "",
    },
    {
      id: 103,
      denumire: "Fermentis SafAle BW-20",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-012",
      lot: "",
    },
    {
      id: 104,
      denumire: "Fermentis SafBrew DA-16",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-013",
      lot: "",
    },
    {
      id: 105,
      denumire: "Fermentis SafBrew DW-17",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-014",
      lot: "",
    },
    {
      id: 106,
      denumire: "Fermentis SafBrew LD-20",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-015",
      lot: "",
    },
    {
      id: 107,
      denumire: "Lallemand Abbaye",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-016",
      lot: "",
    },
    {
      id: 108,
      denumire: "Lallemand Diamond Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-017",
      lot: "",
    },
    {
      id: 109,
      denumire: "Lallemand Farmhouse",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-018",
      lot: "",
    },
    {
      id: 110,
      denumire: "Lallemand Kveik Voss Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-019",
      lot: "",
    },
    {
      id: 111,
      denumire: "Lallemand Munich Classic",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-020",
      lot: "",
    },
    {
      id: 112,
      denumire: "Lallemand Nova Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-021",
      lot: "",
    },
    {
      id: 113,
      denumire: "Lallemand Verdant IPA",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-022",
      lot: "",
    },
    {
      id: 114,
      denumire: "Lallemand Windsor",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-023",
      lot: "",
    },
    {
      id: 115,
      denumire: "Lallemand Wit",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-024",
      lot: "",
    },
    {
      id: 116,
      denumire: "Lallemand WildBrew Philly Sour",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-025",
      lot: "",
    },
    {
      id: 117,
      denumire: "Lallemand WildBrew Sour Pitch",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "DROJDIE-026",
      lot: "",
    },
    {
      id: 118,
      denumire: "Servomyces Lallemand",
      tip: "nutrient",
      cantitate: 0,
      unitate: "gr",
      producator: "Lallemand",
      codProdus: "NUTRIENT-001",
      lot: "",
    },
    {
      id: 119,
      denumire: "White Labs WLP001 California Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-027",
      lot: "",
    },
    {
      id: 120,
      denumire: "White Labs WLP066 London Fog",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-028",
      lot: "",
    },
    {
      id: 121,
      denumire: "White Labs WLP860 Munich Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-029",
      lot: "",
    },
    {
      id: 122,
      denumire: "White Labs WLP002 English Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-030",
      lot: "",
    },
    {
      id: 123,
      denumire: "White Labs WLP004 Irish Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-031",
      lot: "",
    },
    {
      id: 124,
      denumire: "White Labs WLP005 British Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-032",
      lot: "",
    },
    {
      id: 125,
      denumire: "White Labs WLP007 Dry English Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-033",
      lot: "",
    },
    {
      id: 126,
      denumire: "White Labs WLP008 East Coast Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-034",
      lot: "",
    },
    {
      id: 127,
      denumire: "White Labs WLP009 Australian Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-035",
      lot: "",
    },
    {
      id: 128,
      denumire: "White Labs WLP011 European Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-036",
      lot: "",
    },
    {
      id: 129,
      denumire: "White Labs WLP013 London Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-037",
      lot: "",
    },
    {
      id: 130,
      denumire: "White Labs WLP023 Burton Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-038",
      lot: "",
    },
    {
      id: 131,
      denumire: "White Labs WLP028 Edinburgh Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-039",
      lot: "",
    },
    {
      id: 132,
      denumire: "White Labs WLP029 German Ale/Kolsch",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-040",
      lot: "",
    },
    {
      id: 133,
      denumire: "White Labs WLP036 Dusseldorf Alt Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-041",
      lot: "",
    },
    {
      id: 134,
      denumire: "White Labs WLP041 Pacific Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-042",
      lot: "",
    },
    {
      id: 135,
      denumire: "White Labs WLP045 Scotch Whisky",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-043",
      lot: "",
    },
    {
      id: 136,
      denumire: "White Labs WLP050 Tennessee Whiskey",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-044",
      lot: "",
    },
    {
      id: 137,
      denumire: "White Labs WLP051 California Ale V",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-045",
      lot: "",
    },
    {
      id: 138,
      denumire: "White Labs WLP060 American Ale Blend",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-046",
      lot: "",
    },
    {
      id: 139,
      denumire: "White Labs WLP065 American Whiskey",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-047",
      lot: "",
    },
    {
      id: 140,
      denumire: "White Labs WLP070 Kentucky Bourbon",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-048",
      lot: "",
    },
    {
      id: 141,
      denumire: "White Labs WLP078 Neutral Grain",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-049",
      lot: "",
    },
    {
      id: 142,
      denumire: "White Labs WLP080 Cream Ale Blend",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-050",
      lot: "",
    },
    {
      id: 143,
      denumire: "White Labs WLP085 English Ale Blend",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-051",
      lot: "",
    },
    {
      id: 144,
      denumire: "White Labs WLP090 San Diego Super",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-052",
      lot: "",
    },
    {
      id: 145,
      denumire: "White Labs WLP095 Burlington Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-053",
      lot: "",
    },
    {
      id: 146,
      denumire: "White Labs WLP099 Super High Gravity Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-054",
      lot: "",
    },
    {
      id: 147,
      denumire: "White Labs WLP300 Hefeweizen Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-055",
      lot: "",
    },
    {
      id: 148,
      denumire: "White Labs WLP320 American Hefeweizen Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-056",
      lot: "",
    },
    {
      id: 149,
      denumire: "White Labs WLP351 Bavarian Weizen",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-057",
      lot: "",
    },
    {
      id: 150,
      denumire: "White Labs WLP380 Hefeweizen IV Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-058",
      lot: "",
    },
    {
      id: 151,
      denumire: "White Labs WLP400 Belgian Wit Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-059",
      lot: "",
    },
    {
      id: 152,
      denumire: "White Labs WLP410 Belgian Wit II Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-060",
      lot: "",
    },
    {
      id: 153,
      denumire: "White Labs WLP500 Monastery Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-061",
      lot: "",
    },
    {
      id: 154,
      denumire: "White Labs WLP510 Bastogne Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-062",
      lot: "",
    },
    {
      id: 155,
      denumire: "White Labs WLP530 Abbey Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-063",
      lot: "",
    },
    {
      id: 156,
      denumire: "White Labs WLP540 Abbey IV Ale",
      tip: "drojdie",
      cantitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-064",
      lot: "",
    },
    {
      id: 157,
      denumire: "White Labs WLP545 Belgian Strong Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-065",
      lot: "",
    },
    {
      id: 158,
      denumire: "White Labs WLP550 Belgian Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-066",
      lot: "",
    },
    {
      id: 159,
      denumire: "White Labs WLP565 Saison I",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-067",
      lot: "",
    },
    {
      id: 160,
      denumire: "White Labs WLP566 Saison II",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-068",
      lot: "",
    },
    {
      id: 161,
      denumire: "White Labs WLP568 Belgian Style Saison Ale Blend",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-069",
      lot: "",
    },
    {
      id: 162,
      denumire: "White Labs WLP570 Belgian Golden Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-070",
      lot: "",
    },
    {
      id: 163,
      denumire: "White Labs WLP575 Belgian Style Ale Blend",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-071",
      lot: "",
    },
    {
      id: 164,
      denumire: "White Labs WLP590 French Saison Ale",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-072",
      lot: "",
    },
    {
      id: 165,
      denumire: "White Labs WLP800 Pilsner Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-073",
      lot: "",
    },
    {
      id: 166,
      denumire: "White Labs WLP802 Czech Budejovice Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-074",
      lot: "",
    },
    {
      id: 167,
      denumire: "White Labs WLP810 San Francisco Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-075",
      lot: "",
    },
    {
      id: 168,
      denumire: "White Labs WLP820 Oktoberfest/Marzen Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-076",
      lot: "",
    },
    {
      id: 169,
      denumire: "White Labs WLP830 German Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-077",
      lot: "",
    },
    {
      id: 170,
      denumire: "White Labs WLP833 German Bock Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-078",
      lot: "",
    },
    {
      id: 171,
      denumire: "White Labs WLP838 Southern German Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-079",
      lot: "",
    },
    {
      id: 172,
      denumire: "White Labs WLP840 American Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-080",
      lot: "",
    },
    {
      id: 173,
      denumire: "White Labs WLP850 Copenhagen Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-081",
      lot: "",
    },
    {
      id: 174,
      denumire: "White Labs WLP862 Cry Havoc",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-082",
      lot: "",
    },
    {
      id: 175,
      denumire: "White Labs WLP885 Zurich Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-083",
      lot: "",
    },
    {
      id: 176,
      denumire: "White Labs WLP940 Mexican Lager",
      tip: "drojdie",
      cantitate: 0,
      unitate: "gr",
      producator: "White Labs",
      codProdus: "DROJDIE-084",
      lot: "",
    },
    {
      id: 177,
      denumire: "SafCider AB-1",
      tip: "drojdie",
      subcategorie: "cidru",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-085",
      lot: "",
    },
    {
      id: 178,
      denumire: "SafCider AS-2",
      tip: "drojdie",
      subcategorie: "cidru",
      cantitate: 0,
      unitate: "gr",
      producator: "Fermentis",
      codProdus: "DROJDIE-086",
      lot: "",
    },
    {
      id: 179,
      denumire: "Etichetă spate",
      tip: "accesoriu",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "ACCESORIU-003",
      lot: "",
    },
    {
      id: 180,
      denumire: "Sticlă 0.33L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-003",
      lot: "",
    },
    {
      id: 181,
      denumire: "Sticlă 0.75L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-004",
      lot: "",
    },
    {
      id: 182,
      denumire: "Keg 5L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-005",
      lot: "",
    },
    {
      id: 183,
      denumire: "Keg 10L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-006",
      lot: "",
    },
    {
      id: 184,
      denumire: "Keg 15L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-007",
      lot: "",
    },
    {
      id: 185,
      denumire: "Keg 20L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-008",
      lot: "",
    },
    {
      id: 186,
      denumire: "Keg 25L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-009",
      lot: "",
    },
    {
      id: 187,
      denumire: "Keg 30L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-010",
      lot: "",
    },
    {
      id: 188,
      denumire: "Keg 40L",
      tip: "ambalaj",
      cantitate: 0,
      unitate: "buc",
      producator: "Generic Packaging",
      codProdus: "AMBALAJ-011",
      lot: "",
    },
  ];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(materialeInitiale));
}

export function getMateriiPrime() {
  const data = localStorage.getItem(STORAGE_KEY);
  return data ? JSON.parse(data) : [];
}

export function saveMateriiPrime(materiale) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(materiale));
}


export function adaugaSauSuplimenteazaMaterial({ denumire, cantitate, unitate, tip, producator, codProdus, lot, subcategorie }) {
  const materiale = getMateriiPrime();
  const denumireTrim = denumire.trim().toLowerCase();
  const unitateTrim = unitate.trim().toLowerCase();

  const index = materiale.findIndex(
    m => m.denumire.trim().toLowerCase() === denumireTrim &&
         m.unitate.trim().toLowerCase() === unitateTrim
  );

  if (index !== -1) {
    // Suplimentează stocul existent
    materiale[index].cantitate += Number(cantitate);
    if (lot) materiale[index].lot = lot;
  } else {
    // Adaugă material nou
    const newId = materiale.length > 0 ? Math.max(...materiale.map(m => m.id)) + 1 : 1;
    materiale.push({
      id: newId,
      denumire: denumire.trim(),
      tip: tip ? tip.trim() : "",
      subcategorie: subcategorie ? subcategorie.trim() : "",
      cantitate: Number(cantitate),
      unitate: unitate.trim(),
      producator: producator ? producator.trim() : "",
      codProdus: codProdus ? codProdus.trim() : "",
      lot: lot ? lot.trim() : ""
    });
  }

  saveMateriiPrime(materiale);
  return materiale;
}